/**
 * Email Service - Sends reports via Gmail SMTP using Nodemailer
 */
const nodemailer = require('nodemailer');
const fs = require('fs');
require('dotenv').config();

const SMTP_HOST = process.env.SMTP_HOST || 'smtp.gmail.com';
const SMTP_PORT = parseInt(process.env.SMTP_PORT || '587', 10);
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const EMAIL_FROM = process.env.EMAIL_FROM || SMTP_USER;

function createTransporter() {
  if (!SMTP_USER || !SMTP_PASS) {
    console.warn('⚠ SMTP credentials not configured. Email sending will be disabled.');
    console.warn('⚠ Please set SMTP_USER and SMTP_PASS environment variables.');
    return null;
  }

  return nodemailer.createTransport({
    host: SMTP_HOST,
    port: SMTP_PORT,
    secure: SMTP_PORT === 465,
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function validateRecipients(recipients) {
  const list = Array.isArray(recipients) ? recipients : [recipients];
  const valid = list.map((e) => String(e).trim()).filter((e) => EMAIL_RE.test(e));
  const invalid = list.filter((e) => !EMAIL_RE.test(String(e).trim()));
  if (invalid.length > 0) {
    console.warn('⚠ sendReportEmail: skipping invalid addresses:', invalid);
  }
  return valid;
}

/**
 * Send report via Gmail SMTP.
 * @param {string|string[]} to - One or more recipient email addresses
 * @param {string} subject - Email subject
 * @param {string} body - Email body (HTML)
 * @param {string} pdfPath - Path to PDF file
 * @param {string} pdfFilename - PDF filename for attachment
 * @returns {Promise<Object>} Email send result
 */
async function sendReportEmail(to, subject, body, pdfPath, pdfFilename) {
  const transporter = createTransporter();

  if (!transporter) {
    throw new Error('Email service not configured. Please set SMTP_USER and SMTP_PASS environment variables.');
  }

  const recipients = validateRecipients(to);
  if (recipients.length === 0) {
    throw new Error('sendReportEmail: no valid recipient email addresses provided');
  }

  if (!fs.existsSync(pdfPath)) {
    throw new Error(`PDF file not found: ${pdfPath}`);
  }

  const fromAddress = EMAIL_FROM ? `Hadir.AI Reports <${EMAIL_FROM}>` : `Hadir.AI Reports <${SMTP_USER}>`;
  const recipientList = recipients.join(', ');
  const sentAt = new Date().toISOString();

  console.log(`[emailService] Sending report email`);
  console.log(`[emailService]   From:       ${fromAddress}`);
  console.log(`[emailService]   To:         ${recipientList}`);
  console.log(`[emailService]   Subject:    ${subject}`);
  console.log(`[emailService]   Attachment: ${pdfFilename}`);
  console.log(`[emailService]   Timestamp:  ${sentAt}`);

  try {
    const info = await transporter.sendMail({
      from: fromAddress,
      to: recipientList,
      subject,
      html: body,
      attachments: [
        {
          filename: pdfFilename,
          path: pdfPath,
        },
      ],
    });

    console.log(`✓ Report email sent via Gmail SMTP (messageId=${info.messageId}) to: ${recipientList}`);
    return { success: true, messageId: info.messageId, recipients };
  } catch (error) {
    console.error(`✗ Error sending report email to ${recipientList} at ${sentAt}:`, error.message);
    throw error;
  }
}

/**
 * Generate email body for monthly report
 * @param {Object} reportData - Report data (must include reportData.company)
 * @returns {string} HTML email body
 */
function generateMonthlyReportEmailBody(reportData) {
  const companyName = reportData.company?.name || 'Your Company';
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Monthly Attendance Report</h1>
        <h2 style="margin:4px 0;">${companyName}</h2>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Company:</strong> ${companyName}</p>
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This is an automated report generated by Hadir.AI Attendance Management System.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate email body for manual report
 * @param {Object} reportData - Report data (must include reportData.company)
 * @returns {string} HTML email body
 */
function generateManualReportEmailBody(reportData) {
  const companyName = reportData.company?.name || 'Your Company';
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #2196F3; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Attendance Report</h1>
        <h2 style="margin:4px 0;">${companyName}</h2>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Company:</strong> ${companyName}</p>
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This report was generated on request from the Hadir.AI Admin Dashboard.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

module.exports = {
  sendReportEmail,
  generateMonthlyReportEmailBody,
  generateManualReportEmailBody,
};
