/**
 * Email Service - Sends reports via email using Resend API
 */
const { Resend } = require('resend');
const fs = require('fs');
require('dotenv').config();

// Resend API configuration
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const RESEND_FROM_EMAIL = process.env.RESEND_FROM_EMAIL || process.env.EMAIL_FROM || 'reports@hadir.ai';

/**
 * Initialize Resend client
 * @returns {Resend|null} Resend client instance or null if not configured
 */
function createResendClient() {
  if (!RESEND_API_KEY) {
    console.warn('⚠ Resend API key not configured. Email sending will be disabled.');
    console.warn('⚠ Please set RESEND_API_KEY environment variable.');
    return null;
  }

  return new Resend(RESEND_API_KEY);
}

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function validateRecipients(recipients) {
  const list = Array.isArray(recipients) ? recipients : [recipients];
  const valid = list.map((e) => String(e).trim()).filter((e) => EMAIL_RE.test(e));
  const invalid = list.filter((e) => !EMAIL_RE.test(String(e).trim()));
  if (invalid.length > 0) {
    console.warn('⚠ sendReportEmail: skipping invalid addresses:', invalid);
  }
  return valid;
}

/**
 * Send report via email using Resend API.
 * @param {string|string[]} to - One or more recipient email addresses
 * @param {string} subject - Email subject
 * @param {string} body - Email body (HTML)
 * @param {string} pdfPath - Path to PDF file
 * @param {string} pdfFilename - PDF filename for attachment
 * @returns {Promise<Object>} Email send result
 */
async function sendReportEmail(to, subject, body, pdfPath, pdfFilename) {
  const resend = createResendClient();

  if (!resend) {
    throw new Error('Email service not configured. Please set RESEND_API_KEY environment variable.');
  }

  const recipients = validateRecipients(to);
  if (recipients.length === 0) {
    throw new Error('sendReportEmail: no valid recipient email addresses provided');
  }

  if (!fs.existsSync(pdfPath)) {
    throw new Error(`PDF file not found: ${pdfPath}`);
  }

  try {
    const pdfBuffer = fs.readFileSync(pdfPath);
    const pdfBase64 = pdfBuffer.toString('base64');

    const { data, error } = await resend.emails.send({
      from: `Hadir.AI Reports <${RESEND_FROM_EMAIL}>`,
      to: recipients,
      subject: subject,
      html: body,
      attachments: [
        {
          filename: pdfFilename,
          content: pdfBase64,
        },
      ],
    });

    if (error) {
      console.error('✗ Resend API error:', error);
      throw new Error(`Resend API error: ${error.message || JSON.stringify(error)}`);
    }

    if (!data || !data.id) {
      throw new Error('Resend API returned no email ID');
    }

    console.log(`✓ Report email sent via Resend (id=${data.id}) to: ${recipients.join(', ')}`);
    return { success: true, messageId: data.id, recipients };
  } catch (error) {
    console.error('✗ Error sending report email:', error);
    if (error.message?.includes('API key')) {
      throw new Error('Invalid Resend API key. Please check RESEND_API_KEY environment variable.');
    }
    if (error.message?.includes('domain')) {
      throw new Error('Resend domain not verified. Please verify your sending domain in Resend dashboard.');
    }
    throw error;
  }
}

/**
 * Generate email body for monthly report
 * @param {Object} reportData - Report data (must include reportData.company)
 * @returns {string} HTML email body
 */
function generateMonthlyReportEmailBody(reportData) {
  const companyName = reportData.company?.name || 'Your Company';
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Monthly Attendance Report</h1>
        <h2 style="margin:4px 0;">${companyName}</h2>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Company:</strong> ${companyName}</p>
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This is an automated report generated by Hadir.AI Attendance Management System.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate email body for manual report
 * @param {Object} reportData - Report data (must include reportData.company)
 * @returns {string} HTML email body
 */
function generateManualReportEmailBody(reportData) {
  const companyName = reportData.company?.name || 'Your Company';
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #2196F3; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Attendance Report</h1>
        <h2 style="margin:4px 0;">${companyName}</h2>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Company:</strong> ${companyName}</p>
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This report was generated on request from the Hadir.AI Admin Dashboard.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

module.exports = {
  sendReportEmail,
  generateMonthlyReportEmailBody,
  generateManualReportEmailBody,
};

