/**
 * PDF Generator - Professional corporate attendance reports
 */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { DATA_DIR } = require('./reportStorage');

const HADIR_BRAND = { name: 'Hadir.AI', color: '#2563eb' };
const MARGIN = 50;
const PAGE_WIDTH = 595.28;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function fetchImageBuffer(url) {
  return new Promise((resolve) => {
    if (!url) return resolve(null);
    try {
      const client = url.startsWith('https') ? https : http;
      client.get(url, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          fetchImageBuffer(res.headers.location).then(resolve);
          return;
        }
        if (res.statusCode !== 200) return resolve(null);
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
        res.on('error', () => resolve(null));
      }).on('error', () => resolve(null));
    } catch {
      resolve(null);
    }
  });
}

function ensureSpace(doc, needed = 60) {
  if (doc.y + needed > doc.page.height - 70) {
    doc.addPage();
    return true;
  }
  return false;
}

function drawSectionTitle(doc, title, color) {
  ensureSpace(doc, 40);
  doc.moveDown(0.5);
  doc.fontSize(14).fillColor(color).font('Helvetica-Bold').text(title);
  doc.moveDown(0.3);
  doc.strokeColor(color).lineWidth(1.5)
    .moveTo(MARGIN, doc.y).lineTo(PAGE_WIDTH - MARGIN, doc.y).stroke();
  doc.moveDown(0.5);
  doc.fillColor('#111827');
}

function drawKeyValueGrid(doc, items, columns = 2) {
  const colWidth = CONTENT_WIDTH / columns;
  const startY = doc.y;
  items.forEach((item, i) => {
    const col = i % columns;
    const row = Math.floor(i / columns);
    const x = MARGIN + col * colWidth;
    const y = startY + row * 22;
    doc.fontSize(9).fillColor('#6b7280').font('Helvetica').text(item.label, x, y, { width: colWidth - 10 });
    doc.fontSize(11).fillColor('#111827').font('Helvetica-Bold').text(String(item.value), x, y + 12, { width: colWidth - 10 });
  });
  const rows = Math.ceil(items.length / columns);
  doc.y = startY + rows * 34 + 8;
}

function drawTable(doc, headers, rows, colWidths) {
  const rowHeight = 18;
  const tableWidth = colWidths.reduce((a, b) => a + b, 0);
  ensureSpace(doc, rowHeight * (Math.min(rows.length, 3) + 2));

  let y = doc.y;
  doc.fontSize(8).font('Helvetica-Bold').fillColor('#ffffff');
  doc.rect(MARGIN, y, tableWidth, rowHeight).fill('#374151');
  let x = MARGIN;
  headers.forEach((h, i) => {
    doc.fillColor('#ffffff').text(h, x + 4, y + 5, { width: colWidths[i] - 8, lineBreak: false });
    x += colWidths[i];
  });
  y += rowHeight;

  doc.font('Helvetica').fontSize(8);
  rows.forEach((row, ri) => {
    if (y + rowHeight > doc.page.height - 70) {
      doc.addPage();
      y = MARGIN;
    }
    const bg = ri % 2 === 0 ? '#f9fafb' : '#ffffff';
    doc.rect(MARGIN, y, tableWidth, rowHeight).fill(bg);
    x = MARGIN;
    row.forEach((cell, ci) => {
      doc.fillColor('#111827').text(String(cell ?? ''), x + 4, y + 5, { width: colWidths[ci] - 8, lineBreak: false });
      x += colWidths[ci];
    });
    y += rowHeight;
  });
  doc.y = y + 10;
}

function drawBarChart(doc, title, data, color) {
  if (!data || data.length === 0) return;
  ensureSpace(doc, 120);
  doc.fontSize(10).fillColor('#374151').font('Helvetica-Bold').text(title);
  doc.moveDown(0.3);

  const chartHeight = 80;
  const chartY = doc.y;
  const maxVal = Math.max(...data.map((d) => d.value), 1);
  const barWidth = Math.min(40, (CONTENT_WIDTH - 20) / data.length - 8);

  data.slice(0, 12).forEach((item, i) => {
    const barHeight = (item.value / maxVal) * chartHeight;
    const x = MARGIN + i * (barWidth + 8);
    const y = chartY + chartHeight - barHeight;
    doc.rect(x, y, barWidth, barHeight).fill(color);
    doc.fontSize(7).fillColor('#6b7280').text(item.label, x, chartY + chartHeight + 4, { width: barWidth, align: 'center' });
    doc.fontSize(7).fillColor('#111827').text(String(item.value), x, y - 10, { width: barWidth, align: 'center' });
  });

  doc.y = chartY + chartHeight + 24;
}

function addFooters(doc, brandName) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const ts = new Date().toLocaleString();
    doc.fontSize(7).fillColor('#9ca3af').font('Helvetica')
      .text(`Generated by ${brandName} Reporting Service  |  ${ts}`, MARGIN, doc.page.height - 35, {
        width: CONTENT_WIDTH - 60,
        align: 'left',
      });
    doc.text(`Page ${i - range.start + 1} of ${range.count}`, PAGE_WIDTH - MARGIN - 60, doc.page.height - 35, {
      width: 60,
      align: 'right',
    });
  }
}

/**
 * Generate PDF report from report data
 * @param {Object} reportData
 * @returns {Promise<Buffer>}
 */
async function generatePDF(reportData) {
  const brandColor = reportData.company?.primaryColor || HADIR_BRAND.color;
  const brandName = reportData.company?.name || HADIR_BRAND.name;
  const logoBuffer = await fetchImageBuffer(reportData.company?.logoUrl);

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margins: { top: MARGIN, bottom: 60, left: MARGIN, right: MARGIN }, bufferPages: true });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Cover header band
      doc.rect(0, 0, PAGE_WIDTH, 110).fill(brandColor);
      if (logoBuffer) {
        try {
          doc.image(logoBuffer, MARGIN, 20, { width: 50, height: 50, fit: [50, 50] });
        } catch (_) {}
      }
      doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold')
        .text('Attendance Report', logoBuffer ? MARGIN + 60 : MARGIN, 28);
      doc.fontSize(12).font('Helvetica')
        .text(brandName, logoBuffer ? MARGIN + 60 : MARGIN, 54)
        .text(reportData.period.label, logoBuffer ? MARGIN + 60 : MARGIN, 72);

      doc.fillColor('#111827');
      doc.y = 130;

      drawKeyValueGrid(doc, [
        { label: 'Generation Date', value: new Date(reportData.meta?.generatedAt || Date.now()).toLocaleString() },
        { label: 'Reporting Period', value: reportData.period.label },
        { label: 'Prepared For', value: brandName },
        { label: 'Prepared By', value: reportData.meta?.generatedBy || 'Hadir.AI' },
      ]);

      // Executive Summary
      drawSectionTitle(doc, 'Executive Summary', brandColor);
      const ex = reportData.executive || reportData.overall;
      drawKeyValueGrid(doc, [
        { label: 'Total Employees', value: ex.totalEmployees },
        { label: 'Present', value: ex.present ?? '—' },
        { label: 'Absent', value: ex.absent ?? '—' },
        { label: 'Late', value: ex.late ?? '—' },
        { label: 'Leave', value: ex.leave ?? '—' },
        { label: 'Attendance Rate', value: ex.attendanceRate },
        { label: 'Pending Leaves', value: ex.pendingLeaves },
        { label: 'Open Tickets', value: ex.openTickets },
      ], 4);

      // Attendance Statistics
      if (reportData.attendanceStats) {
        drawSectionTitle(doc, 'Attendance Statistics', brandColor);
        const t = reportData.attendanceStats.totals;
        drawKeyValueGrid(doc, [
          { label: 'Total Check-ins', value: t.checkins },
          { label: 'Total Check-outs', value: t.checkouts },
          { label: 'Avg Check-ins/Day', value: t.avgCheckinsPerDay },
          { label: 'Avg Work Hours/Day', value: t.avgWorkHours },
          { label: 'Late Arrivals', value: t.lateArrivals },
        ], 3);
      }

      // Department Breakdown
      if (reportData.departments?.length) {
        drawSectionTitle(doc, 'Department Breakdown', brandColor);
        drawTable(doc,
          ['Department', 'Employees', 'Present', 'Absent', 'Attendance %'],
          reportData.departments.map((d) => [d.name, d.employees, d.present ?? '—', d.absent ?? '—', d.attendanceRate]),
          [120, 60, 60, 60, 70]
        );
      }

      // Leave Summary
      if (reportData.leaveSummary) {
        drawSectionTitle(doc, 'Leave Summary', brandColor);
        const ls = reportData.leaveSummary;
        drawKeyValueGrid(doc, [
          { label: 'Pending', value: ls.pending },
          { label: 'Approved', value: ls.approved },
          { label: 'Rejected', value: ls.rejected },
        ], 3);
        if (ls.byType?.length) {
          drawTable(doc,
            ['Leave Type', 'Pending', 'Approved', 'Rejected'],
            ls.byType.map((l) => [l.type, l.pending, l.approved, l.rejected]),
            [140, 70, 70, 70]
          );
        }
      }

      // Work Mode Distribution
      if (reportData.workMode) {
        drawSectionTitle(doc, 'Work Mode Distribution', brandColor);
        const wm = reportData.workMode;
        drawKeyValueGrid(doc, [
          { label: 'Office', value: wm.office },
          { label: 'Hybrid', value: wm.hybrid },
          { label: 'Remote', value: wm.remote },
          { label: 'Other', value: wm.other },
        ], 4);
      }

      // Charts
      if (reportData.charts) {
        drawSectionTitle(doc, 'Analytics', brandColor);
        drawBarChart(doc, 'Attendance Trend', reportData.charts.attendanceTrend, brandColor);
        ensureSpace(doc, 120);
        drawBarChart(doc, 'Department Comparison (%)', reportData.charts.departmentComparison, '#059669');
        ensureSpace(doc, 120);
        drawBarChart(doc, 'Leave Distribution', reportData.charts.leaveDistribution, '#d97706');
        ensureSpace(doc, 120);
        drawBarChart(doc, 'Work Mode Distribution', reportData.charts.workModeDistribution, '#7c3aed');
      }

      // Employee Attendance Table
      if (reportData.employees?.length) {
        drawSectionTitle(doc, 'Employee Attendance', brandColor);
        const empRows = reportData.employees.slice(0, 100).map((e) => [
          e.name, e.department, e.workingDays, e.present, e.absent, e.late, e.leave, e.attendanceRate, e.hoursWorked,
        ]);
        drawTable(doc,
          ['Employee', 'Dept', 'Days', 'Present', 'Absent', 'Late', 'Leave', 'Rate', 'Hours'],
          empRows,
          [80, 55, 35, 42, 42, 35, 35, 42, 42]
        );
        if (reportData.employees.length > 100) {
          doc.fontSize(8).fillColor('#6b7280').text(`Showing first 100 of ${reportData.employees.length} employees.`);
        }
      }

      addFooters(doc, brandName);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

async function savePDFToFile(pdfBuffer, filename) {
  if (!Buffer.isBuffer(pdfBuffer)) {
    throw new Error('savePDFToFile: expected a Buffer, received invalid PDF data');
  }
  if (pdfBuffer.length < 100 || pdfBuffer.slice(0, 4).toString() !== '%PDF') {
    throw new Error('savePDFToFile: invalid PDF buffer — file does not start with %PDF');
  }

  return new Promise((resolve, reject) => {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }
      const filePath = path.join(DATA_DIR, filename);
      fs.writeFile(filePath, pdfBuffer, (err) => {
        if (err) reject(err);
        else resolve(filePath);
      });
    } catch (error) {
      reject(error);
    }
  });
}

function deletePDFFile(filePath) {
  try {
    if (filePath && fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  } catch (error) {
    console.error('[pdfGenerator] Error deleting PDF file:', error.message);
  }
}

function buildDownloadFilename(reportData, reportId) {
  const period = (reportData?.period?.label || 'report').replace(/[^a-z0-9]+/gi, '_');
  const type = (reportData?.period?.type || 'report').replace(/[^a-z0-9]+/gi, '_');
  return `${type}_Report_${period}_${reportId.slice(0, 8)}.pdf`;
}

module.exports = {
  generatePDF,
  savePDFToFile,
  deletePDFFile,
  buildDownloadFilename,
};
