/**
 * PDF Generator — enterprise attendance reports (PDFKit)
 */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { DATA_DIR } = require('./reportStorage');

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const M = { top: 56, bottom: 52, left: 48, right: 48 };
const CONTENT_W = PAGE_W - M.left - M.right;
const BODY_MAX_Y = PAGE_H - M.bottom - 18;
const FOOTER_Y = PAGE_H - M.bottom + 10;

const COLORS = {
  text: '#111827',
  muted: '#6b7280',
  light: '#9ca3af',
  border: '#e5e7eb',
  headerBg: '#1e3a5f',
  rowAlt: '#f8fafc',
  rowHi: '#ecfdf5',
  rowLo: '#fef2f2',
  chart: ['#2563eb', '#059669', '#d97706', '#7c3aed'],
};

function fetchImageBuffer(url) {
  return new Promise((resolve) => {
    if (!url) return resolve(null);
    try {
      const client = url.startsWith('https') ? https : http;
      client.get(url, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          fetchImageBuffer(res.headers.location).then(resolve);
          return;
        }
        if (res.statusCode !== 200) return resolve(null);
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
        res.on('error', () => resolve(null));
      }).on('error', () => resolve(null));
    } catch {
      resolve(null);
    }
  });
}

/** Layout context — manual Y tracking avoids PDFKit flow cursor page-break bugs */
function createLayout(doc) {
  let y = M.top;

  const sync = () => { doc.x = M.left; doc.y = y; };

  const remaining = () => BODY_MAX_Y - y;

  const ensure = (need) => {
    if (remaining() < need) {
      doc.addPage();
      y = M.top;
      sync();
      return true;
    }
    return false;
  };

  const advance = (dy) => { y += dy; sync(); };

  const set = (ny) => { y = ny; sync(); };

  return { get y() { return y; }, ensure, advance, set, sync, remaining };
}

function stampFooters(doc, brandName, generatedAt) {
  const range = doc.bufferedPageRange();
  const total = range.count;
  for (let i = 0; i < total; i++) {
    doc.switchToPage(range.start + i);
    doc.save();
    doc.strokeColor(COLORS.border).lineWidth(0.5)
      .moveTo(M.left, FOOTER_Y - 6).lineTo(PAGE_W - M.right, FOOTER_Y - 6).stroke();
    doc.fontSize(7).fillColor(COLORS.light).font('Helvetica');
    doc.text(
      `Generated by Hadir.AI  |  ${generatedAt}  |  Confidential  |  ${brandName}`,
      M.left, FOOTER_Y, { width: CONTENT_W - 44, lineBreak: false }
    );
    doc.text(`Page ${i + 1} of ${total}`, PAGE_W - M.right - 52, FOOTER_Y, { width: 52, align: 'right', lineBreak: false });
    doc.restore();
  }
}

function drawSection(L, doc, title, color) {
  L.ensure(34);
  L.advance(8);
  const ty = L.y;
  doc.fontSize(13).fillColor(color).font('Helvetica-Bold')
    .text(title, M.left, ty, { width: CONTENT_W, lineBreak: false });
  const ly = ty + 18;
  doc.strokeColor(color).lineWidth(1.2).moveTo(M.left, ly).lineTo(PAGE_W - M.right, ly).stroke();
  L.set(ly + 12);
  doc.fillColor(COLORS.text);
}

function drawEmpty(L, doc, msg) {
  L.ensure(32);
  doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica-Oblique')
    .text(msg, M.left, L.y, { width: CONTENT_W, align: 'center', lineBreak: false });
  L.advance(28);
}

function drawMeta(L, doc, items) {
  L.ensure(44);
  const ty = L.y;
  const colW = CONTENT_W / items.length;
  items.forEach((item, i) => {
    const x = M.left + i * colW;
    doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica').text(item.label, x, ty, { width: colW - 6, lineBreak: false });
    doc.fontSize(9).fillColor(COLORS.text).font('Helvetica-Bold').text(String(item.value), x, ty + 12, { width: colW - 6, lineBreak: false });
  });
  L.set(ty + 32);
}

function drawKpis(L, doc, items, color, cols = 3) {
  const cardH = 44;
  const gap = 8;
  const cardW = (CONTENT_W - gap * (cols - 1)) / cols;
  const rows = Math.ceil(items.length / cols);
  L.ensure(rows * (cardH + gap) + 6);
  const startY = L.y;

  items.forEach((item, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = M.left + col * (cardW + gap);
    const cy = startY + row * (cardH + gap);
    doc.roundedRect(x, cy, cardW, cardH, 4).fillAndStroke('#f8fafc', COLORS.border);
    doc.fontSize(7.5).fillColor(COLORS.muted).font('Helvetica').text(item.label, x + 8, cy + 7, { width: cardW - 16, lineBreak: false });
    doc.fontSize(13).fillColor(color).font('Helvetica-Bold').text(String(item.value), x + 8, cy + 21, { width: cardW - 16, lineBreak: false });
  });
  L.set(startY + rows * (cardH + gap) + 4);
}

function drawTable(L, doc, headers, rows, colWidths, opts = {}) {
  const rowH = opts.rowH || 20;
  const headH = rowH + 2;
  const tableW = colWidths.reduce((a, b) => a + b, 0);

  const paintHeader = (hy) => {
    doc.rect(M.left, hy, tableW, headH).fill(COLORS.headerBg);
    let x = M.left;
    doc.fontSize(7.5).font('Helvetica-Bold').fillColor('#fff');
    headers.forEach((h, i) => {
      doc.text(h, x + 4, hy + 5, { width: colWidths[i] - 8, lineBreak: false });
      x += colWidths[i];
    });
    return hy + headH;
  };

  if (!rows.length) {
    drawEmpty(L, doc, 'No data available for this section.');
    return;
  }

  L.ensure(headH + rowH + 4);
  let ry = paintHeader(L.y);

  rows.forEach((row, ri) => {
    if (ry + rowH > BODY_MAX_Y) {
      doc.addPage();
      L.set(M.top);
      ry = paintHeader(L.y);
    }
    let bg = ri % 2 === 0 ? '#fff' : COLORS.rowAlt;
    if (opts.hiFirst && ri === 0) bg = COLORS.rowHi;
    if (opts.loLast && ri === rows.length - 1 && rows.length > 1) bg = COLORS.rowLo;
    doc.rect(M.left, ry, tableW, rowH).fill(bg);
    let x = M.left;
    doc.fontSize(7.5).font('Helvetica').fillColor(COLORS.text);
    row.forEach((cell, ci) => {
      doc.text(String(cell ?? '—'), x + 4, ry + 5, { width: colWidths[ci] - 8, lineBreak: false });
      x += colWidths[ci];
    });
    ry += rowH;
  });
  L.set(ry + 8);
}

function drawChartBox(doc, x, cy, w, h, title, data, color) {
  doc.roundedRect(x, cy, w, h, 4).stroke(COLORS.border);
  doc.fontSize(9).fillColor(COLORS.text).font('Helvetica-Bold')
    .text(title, x + 8, cy + 7, { width: w - 16, lineBreak: false });

  if (!data?.length || data.every((d) => !d.value)) {
    doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica-Oblique')
      .text('No data', x + 8, cy + h / 2 - 4, { width: w - 16, align: 'center', lineBreak: false });
    return;
  }

  const plotX = x + 10;
  const plotY = cy + 24;
  const plotW = w - 20;
  const plotH = h - 36;
  const slice = data.slice(0, 8);
  const maxV = Math.max(...slice.map((d) => d.value), 1);
  const barW = Math.max(10, (plotW - (slice.length - 1) * 4) / slice.length);

  slice.forEach((d, i) => {
    const bh = Math.max(2, (d.value / maxV) * plotH);
    const bx = plotX + i * (barW + 4);
    const by = plotY + plotH - bh;
    doc.rect(bx, by, barW, bh).fill(color);
    doc.fontSize(6).fillColor(COLORS.muted).font('Helvetica')
      .text(d.label, bx, plotY + plotH + 2, { width: barW, align: 'center', lineBreak: false });
  });
}

function drawChartGrid(L, doc, charts, brandColor) {
  const specs = [
    ['Attendance Trend', charts.attendanceTrend, brandColor],
    ['Department Attendance %', charts.departmentComparison, COLORS.chart[1]],
    ['Leave Distribution', charts.leaveDistribution, COLORS.chart[2]],
    ['Work Mode', charts.workModeDistribution, COLORS.chart[3]],
  ];
  const gap = 12;
  const cw = (CONTENT_W - gap) / 2;
  const ch = 128;
  const rowH = ch + gap;
  L.ensure(rowH * 2 + 4);
  const sy = L.y;

  for (let i = 0; i < specs.length; i += 2) {
    const row = i / 2;
    const cy = sy + row * rowH;
    drawChartBox(doc, M.left, cy, cw, ch, specs[i][0], specs[i][1], specs[i][2]);
    if (specs[i + 1]) {
      drawChartBox(doc, M.left + cw + gap, cy, cw, ch, specs[i + 1][0], specs[i + 1][1], specs[i + 1][2]);
    }
  }
  L.set(sy + rowH * 2);
}

function drawCover(L, doc, reportData, logoBuffer, brandColor, brandName) {
  const headerH = 96;
  doc.rect(0, 0, PAGE_W, headerH).fill(brandColor);
  const tx = logoBuffer ? M.left + 56 : M.left;
  if (logoBuffer) {
    try { doc.image(logoBuffer, M.left, 20, { fit: [44, 44] }); } catch (_) {}
  }
  doc.fillColor('#fff');
  doc.fontSize(19).font('Helvetica-Bold').text('Attendance & Analytics Report', tx, 22, { width: CONTENT_W - 50, lineBreak: false });
  doc.fontSize(12).font('Helvetica-Bold').text(brandName, tx, 48, { lineBreak: false });
  doc.fontSize(9).font('Helvetica').text(reportData.period.label, tx, 64, { lineBreak: false });
  L.set(headerH + 14);
  doc.fillColor(COLORS.text);

  drawMeta(L, doc, [
    { label: 'Generation Date', value: new Date(reportData.meta?.generatedAt || Date.now()).toLocaleString() },
    { label: 'Reporting Period', value: reportData.period.label },
    { label: 'Prepared For', value: brandName },
    { label: 'Prepared By', value: reportData.meta?.generatedBy || 'Hadir.AI' },
  ]);
}

async function generatePDF(reportData) {
  const brandColor = reportData.company?.primaryColor || COLORS.chart[0];
  const brandName = reportData.company?.name || 'Hadir.AI';
  const logoBuffer = await fetchImageBuffer(reportData.company?.logoUrl);
  const generatedAt = new Date().toLocaleString();
  const hasData = (reportData.executive?.employeesWithAttendance || 0) > 0
    || (reportData.attendanceStats?.totals?.checkins || 0) > 0;

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: M.top, bottom: M.bottom, left: M.left, right: M.right },
        bufferPages: true,
      });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const L = createLayout(doc);
      L.sync();

      drawCover(L, doc, reportData, logoBuffer, brandColor, brandName);

      const ex = reportData.executive || {};
      drawSection(L, doc, 'Executive Summary', brandColor);
      if (!hasData && (ex.totalEmployees || 0) > 0) {
        drawEmpty(L, doc, 'No attendance data available for this reporting period.');
      }
      drawKpis(L, doc, [
        { label: 'Total Employees', value: ex.totalEmployees ?? 0 },
        { label: 'Present (person-days)', value: ex.present ?? 0 },
        { label: 'Absent (person-days)', value: ex.absent ?? 0 },
        { label: 'Leave (person-days)', value: ex.leave ?? 0 },
        { label: 'Late (days)', value: ex.late ?? 0 },
        { label: 'Company Attendance Rate', value: ex.attendanceRate ?? '0%' },
        { label: 'Avg Employee Rate', value: ex.avgEmployeeAttendanceRate ?? '0%' },
        { label: 'Avg Hours / Employee', value: ex.avgHours ?? 0 },
        { label: 'Pending Requests', value: ex.pendingLeaves ?? 0 },
        { label: 'Open Tickets', value: ex.openTickets ?? 0 },
      ], brandColor, 3);

      const t = reportData.attendanceStats?.totals || {};
      drawSection(L, doc, 'Attendance Statistics', brandColor);
      drawKpis(L, doc, [
        { label: 'Total Check-ins', value: t.checkins ?? 0 },
        { label: 'Total Check-outs', value: t.checkouts ?? 0 },
        { label: 'Avg Check-in Time', value: t.avgCheckInTime ?? '—' },
        { label: 'Avg Check-out Time', value: t.avgCheckOutTime ?? '—' },
        { label: 'Avg Hours Worked', value: t.avgWorkHours ?? 0 },
        { label: 'Avg Late Minutes', value: t.avgLateMinutes ?? 0 },
        { label: 'Late Arrivals', value: t.lateArrivals ?? 0 },
        { label: 'Office Employees', value: reportData.workMode?.office ?? 0 },
        { label: 'Hybrid Employees', value: reportData.workMode?.hybrid ?? 0 },
        { label: 'Remote Employees', value: reportData.workMode?.remote ?? 0 },
      ], brandColor, 3);

      drawSection(L, doc, 'Department Breakdown', brandColor);
      const depts = reportData.departments || [];
      drawTable(L, doc,
        ['Department', 'Emp', 'Present', 'Absent', 'Leave', 'Late', 'Attend %', 'Avg Hrs'],
        depts.map((d) => [d.name, d.employees, d.present, d.absent, d.leave, d.late, d.attendanceRate, d.avgHours]),
        [95, 32, 42, 42, 38, 32, 48, 42],
        { hiFirst: true, loLast: true }
      );

      if (reportData.leaveSummary) {
        const ls = reportData.leaveSummary;
        drawSection(L, doc, 'Leave Summary', brandColor);
        drawKpis(L, doc, [
          { label: 'Pending', value: ls.pending },
          { label: 'Approved', value: ls.approved },
          { label: 'Rejected', value: ls.rejected },
        ], brandColor, 3);
        if (ls.byType?.length) {
          drawTable(L, doc, ['Leave Type', 'Pending', 'Approved', 'Rejected'],
            ls.byType.map((l) => [l.type, l.pending, l.approved, l.rejected]),
            [160, 70, 70, 70]);
        }
      }

      if (hasData && reportData.charts) {
        drawSection(L, doc, 'Analytics', brandColor);
        drawChartGrid(L, doc, reportData.charts, brandColor);
      }

      drawSection(L, doc, 'Employee Attendance', brandColor);
      const employees = reportData.employees || [];
      drawTable(L, doc,
        ['Employee', 'Dept', 'Days', 'Present', 'Absent', 'Leave', 'Late', 'Rate', 'Hours', 'OT'],
        employees.slice(0, 200).map((e) => [
          e.name, e.department, e.workingDays, e.present, e.absent, e.leave, e.late,
          e.attendanceRate, e.hoursWorked, e.overtime ?? 0,
        ]),
        [72, 52, 30, 38, 38, 34, 30, 36, 38, 28]
      );
      if (employees.length > 200) {
        L.ensure(16);
        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica')
          .text(`Showing first 200 of ${employees.length} employees.`, M.left, L.y, { width: CONTENT_W, lineBreak: false });
        L.advance(14);
      }

      stampFooters(doc, brandName, generatedAt);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

async function savePDFToFile(pdfBuffer, filename) {
  if (!Buffer.isBuffer(pdfBuffer)) throw new Error('savePDFToFile: expected a Buffer');
  if (pdfBuffer.slice(0, 4).toString() !== '%PDF') throw new Error('savePDFToFile: invalid PDF buffer');

  return new Promise((resolve, reject) => {
    if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
    fs.writeFile(path.join(DATA_DIR, filename), pdfBuffer, (err) => {
      if (err) reject(err);
      else resolve(path.join(DATA_DIR, filename));
    });
  });
}

function deletePDFFile(filePath) {
  try { if (filePath && fs.existsSync(filePath)) fs.unlinkSync(filePath); } catch (_) {}
}

function buildDownloadFilename(reportData, reportId) {
  const period = (reportData?.period?.label || 'report').replace(/[^a-z0-9]+/gi, '_');
  const type = (reportData?.period?.type || 'report').replace(/[^a-z0-9]+/gi, '_');
  return `${type}_Report_${period}_${reportId.slice(0, 8)}.pdf`;
}

module.exports = { generatePDF, savePDFToFile, deletePDFFile, buildDownloadFilename };
